In [186]:
import pandas as pd
import numpy as np
import camelot
from functools import reduce
from pathlib import Path

# Abay oblast and East-Kazakhstan oblast

Since these two oblasts were divided in 2022, we will need to recombine rayon level data for both.

## Investments

### 2022-2024

In [2]:
abay_all_2022 = pd.read_excel("../Data/Investments/Abay/2022_Investments.xlsx", sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_all_2023 = pd.read_excel("../Data/Investments/Abay/2023_Investments.xlsx", sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_all_2024 = pd.read_excel("../Data/Investments/Abay/2024_Investments.xlsx", sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [3]:
abay_non_2022 = pd.read_excel("../Data/Investments/Abay/2022_Investments.xlsx", sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_non_2023 = pd.read_excel("../Data/Investments/Abay/2023_Investments.xlsx", sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
abay_non_2024 = pd.read_excel("../Data/Investments/Abay/2024_Investments.xlsx", sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [4]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [abay_all_2022, abay_all_2023, abay_all_2024]:
    df.columns = all_columns

for df in [abay_non_2022, abay_non_2023, abay_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [5]:
abay_all_2024.loc[0, ['l_all_inv', 'f_all_inv']] = abay_all_2024.loc[0, ['l_all_inv', 'f_all_inv']] + abay_all_2024.loc[7, ['l_all_inv', 'f_all_inv']]
abay_all_2024.loc[11, ['l_all_inv', 'f_all_inv']] = abay_all_2024.loc[10, ['l_all_inv', 'f_all_inv']] + abay_all_2024.loc[11, ['l_all_inv', 'f_all_inv']]
abay_all_2024 = abay_all_2024.drop([7, 10]).reset_index(drop=True)

abay_non_2024.loc[0, ['l_nonextr_inv', 'f_nonextr_inv']] = abay_non_2024.loc[0, ['l_nonextr_inv', 'f_nonextr_inv']] + abay_non_2024.loc[7, ['l_nonextr_inv', 'f_nonextr_inv']]
abay_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']] = abay_non_2024.loc[10, ['l_nonextr_inv', 'f_nonextr_inv']] + abay_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']]
abay_non_2024 = abay_non_2024.drop([7, 10]).reset_index(drop=True)

In [6]:
rayon_names = ['Semey_city', 'Kurchatov_city', 'Abay', 'Aksuat', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Zharma', 'Kokpekti', 'Urzhar']

for df in [abay_all_2022, abay_all_2023, abay_all_2024, abay_non_2022, abay_non_2023, abay_non_2024]:
    df['rayon'] = rayon_names

In [7]:
abay_2022 = abay_all_2022.merge(abay_non_2022, on='rayon')
abay_2023 = abay_all_2023.merge(abay_non_2023, on='rayon')
abay_2024 = abay_all_2024.merge(abay_non_2024, on='rayon')

In [8]:
dfs = [abay_2022, abay_2023, abay_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [9]:
ek_all_2022 = pd.read_excel("../Data/Investments/East-Kazakhstan/2022_Investments.xlsx", sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_all_2023 = pd.read_excel("../Data/Investments/East-Kazakhstan/2023_Investments.xlsx", sheet_name='19', header=4, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_all_2024 = pd.read_excel("../Data/Investments/East-Kazakhstan/2024_Investments.xlsx", sheet_name='14', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [10]:
ek_non_2022 = pd.read_excel("../Data/Investments/East-Kazakhstan/2022_Investments.xlsx", sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_non_2023 = pd.read_excel("../Data/Investments/East-Kazakhstan/2023_Investments.xlsx", sheet_name='20', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ek_non_2024 = pd.read_excel("../Data/Investments/East-Kazakhstan/2024_Investments.xlsx", sheet_name='15', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [11]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [ek_all_2022, ek_all_2023, ek_all_2024]:
    df.columns = all_columns

for df in [ek_non_2022, ek_non_2023, ek_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [12]:
ek_all_2024.loc[5, ['l_all_inv', 'f_all_inv']] = ek_all_2024.loc[5, ['l_all_inv', 'f_all_inv']] + ek_all_2024.loc[7, ['l_all_inv', 'f_all_inv']]
ek_all_2024.loc[6, ['l_all_inv', 'f_all_inv']] = ek_all_2024.loc[6, ['l_all_inv', 'f_all_inv']] + ek_all_2024.loc[11, ['l_all_inv', 'f_all_inv']]
ek_all_2024 = ek_all_2024.drop([7, 11]).reset_index(drop=True)

ek_non_2024.loc[5, ['l_nonextr_inv', 'f_nonextr_inv']] = ek_non_2024.loc[5, ['l_nonextr_inv', 'f_nonextr_inv']] + ek_non_2024.loc[7, ['l_nonextr_inv', 'f_nonextr_inv']]
ek_non_2024.loc[6, ['l_nonextr_inv', 'f_nonextr_inv']] = ek_non_2024.loc[6, ['l_nonextr_inv', 'f_nonextr_inv']] + ek_non_2024.loc[11, ['l_nonextr_inv', 'f_nonextr_inv']]
ek_non_2024 = ek_non_2024.drop([7, 11]).reset_index(drop=True)

In [13]:
rayon_names = ['Oskemen_city', 'Ridder_city', 'Glubokoe', 'Zaysan', 'Altay', 'Kurshim', 'Katonkaragay', 'Samar', 'Tarbagatay', 'Ulan', 'Shemonaiha']

for df in [ek_all_2022, ek_all_2023, ek_all_2024, ek_non_2022, ek_non_2023, ek_non_2024]:
    df['rayon'] = rayon_names

In [14]:
ek_2022 = ek_all_2022.merge(ek_non_2022, on='rayon')
ek_2023 = ek_all_2023.merge(ek_non_2023, on='rayon')
ek_2024 = ek_all_2024.merge(ek_non_2024, on='rayon')

In [15]:
dfs = [ek_2022, ek_2023, ek_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [16]:
east_2022 = pd.concat([abay_2022, ek_2022], ignore_index=True)
east_2023 = pd.concat([abay_2023, ek_2023], ignore_index=True)
east_2024 = pd.concat([abay_2024, ek_2024], ignore_index=True)

In [17]:
east_2022.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2022.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2022.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2022.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2022.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2022.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2022 = east_2022.drop([3, 17]).reset_index(drop=True)

east_2023.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2023.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2023.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2023.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2023.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2023.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2023 = east_2023.drop([3, 17]).reset_index(drop=True)

east_2024.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2024.loc[18, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2024.loc[3, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2024.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = east_2024.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + east_2024.loc[17, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
east_2024 = east_2024.drop([3, 17]).reset_index(drop=True)

### 2018-2021

In [18]:
east_all_2018 = camelot.read_pdf("../Data/Investments/East-Kazakhstan/2018_Investments.pdf", pages='28', flavor='stream')[0].df
east_nonextr_2018 = camelot.read_pdf("../Data/Investments/East-Kazakhstan/2018_Investments.pdf", pages='29', flavor='stream')[0].df

In [19]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

east_all_2018 = east_all_2018[[0, 2, 5]]
east_all_2018 = east_all_2018.drop([0, 1, 2, 3, 4]).reset_index(drop=True)
east_all_2018.columns = all_columns
east_all_2018['rayon'] = rayons
east_all_2018['l_all_inv'] = east_all_2018['l_all_inv'].str.replace(' ', '').astype(int)
east_all_2018['f_all_inv'] = east_all_2018['f_all_inv'].str.replace(' ', '').astype(int)

east_nonextr_2018 = east_nonextr_2018[[0, 2, 5]]
east_nonextr_2018 = east_nonextr_2018.drop([0, 1, 2, 3, 4]).reset_index(drop=True)
east_nonextr_2018.columns = non_columns
east_nonextr_2018['all_nonextr_inv'] = east_nonextr_2018['all_nonextr_inv'].str.replace(' ', '').astype(int)
east_nonextr_2018['f_nonextr_inv'] = east_nonextr_2018['f_nonextr_inv'].str.replace(' ', '').astype(int)
east_nonextr_2018['l_nonextr_inv'] = east_nonextr_2018['all_nonextr_inv'] - east_nonextr_2018['f_nonextr_inv']
east_nonextr_2018 = east_nonextr_2018.drop('all_nonextr_inv', axis=1)
east_nonextr_2018['rayon'] = rayons

In [20]:
east_2018 = east_all_2018.merge(east_nonextr_2018, on='rayon')
east_2018['oblast'] = 'East-Kazakhstan'
east_2018['year'] = 2018

In [21]:
east_all_2019 = pd.read_excel("../Data/Investments/East-Kazakhstan/2019_Investments.xls", sheet_name='14', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2019 = pd.read_excel("../Data/Investments/East-Kazakhstan/2019_Investments.xls", sheet_name='15', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop([0, 20, 21, 22]).reset_index(drop=True)

east_all_2020 = pd.read_excel("../Data/Investments/East-Kazakhstan/2020_Investments.xlsx", sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2020 = pd.read_excel("../Data/Investments/East-Kazakhstan/2020_Investments.xlsx", sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

east_all_2021 = pd.read_excel("../Data/Investments/East-Kazakhstan/2021_Investments.xlsx", sheet_name='13', header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
east_nonextr_2021 = pd.read_excel("../Data/Investments/East-Kazakhstan/2021_Investments.xlsx", sheet_name='14', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [22]:
rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [east_all_2019, east_all_2020, east_all_2021]:
    df.columns = all_columns
    df['rayon'] = rayons

for df in [east_nonextr_2019, east_nonextr_2020, east_nonextr_2021]:
    df.columns = non_columns
    df['rayon'] = rayons
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

In [23]:
east_2019 = east_all_2019.merge(east_nonextr_2019, on='rayon')
east_2020 = east_all_2020.merge(east_nonextr_2020, on='rayon')
east_2021 = east_all_2021.merge(east_nonextr_2021, on='rayon')

In [24]:
dfs = [east_2019, east_2020, east_2021]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'East-Kazakhstan'
    if i == 0:
        df['year'] = 2019
    elif i == 1:
        df['year'] = 2020
    else:
        df['year'] = 2021

In [25]:
east_inv = pd.concat([east_2018, east_2019, east_2020, east_2021, east_2022, east_2023, east_2024], ignore_index=True)
east_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Oskemen_city,118861638,8712430.0,8139851.0,85817952.0,East-Kazakhstan,2018
1,Kurchatov_city,5246007,149907.0,136764.0,2343776.0,East-Kazakhstan,2018
2,Ridder_city,24795133,413071.0,413071.0,5428607.0,East-Kazakhstan,2018
3,Semey_city,59960428,7947330.0,7823433.0,30683044.0,East-Kazakhstan,2018
4,Abay,2868180,3092.0,3092.0,981955.0,East-Kazakhstan,2018
...,...,...,...,...,...,...,...
128,Kurshim,35094458,177293.0,177293.0,5181927.0,East-Kazakhstan,2024
129,Katonkaragay,24393822,513.0,513.0,11539800.0,East-Kazakhstan,2024
130,Tarbagatay,32015111,8251464.0,8178190.0,11248329.0,East-Kazakhstan,2024
131,Ulan,17831632,3100990.0,2650866.0,3644444.0,East-Kazakhstan,2024
132,Shemonaiha,35546797,436488.0,398723.0,1846726.0,East-Kazakhstan,2024

## Employment

### 2022-2024

In [26]:
abay_empl = pd.read_excel("../Data/Employment/Abay.xlsx", skiprows=22, nrows=10, header=None, usecols=[0, 1, 2, 3])

In [27]:
abay_empl.columns = ['rayon', 2022, 2023, 2024]

rayons = ['Semey_city', 'Kurchatov_city', 'Abay', 'Aksuat', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Zharma', 'Kokpekti', 'Urzhar']

abay_empl['rayon'] = rayons

abay_empl[2022] = abay_empl[2022].str.replace(',', '.').astype(float)
abay_empl[2023] = abay_empl[2023].astype(float)
abay_empl[2024] = abay_empl[2024].astype(float)

In [28]:
ek_empl = pd.read_excel("../Data/Employment/East-Kazakhstan.xlsx", skiprows=30, nrows=20, header=None, usecols='A, J, K, L', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [29]:
ek_empl.columns = ['rayon', 2022, 2023, 2024]

rayons = ['Oskemen_city', 'Ridder_city', 'Glubokoe', 'Zaysan', 'Altay', 'Samar', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Shemonaiha']

ek_empl['rayon'] = rayons

ek_empl[2022] = ek_empl[2022].astype(float)
ek_empl[2023] = ek_empl[2023].astype(float)
ek_empl[2024] = ek_empl[2024].astype(float)

In [30]:
east_empl = pd.concat([abay_empl, ek_empl], ignore_index=True)

In [31]:
east_empl.loc[8, [2022, 2023, 2024]] = east_empl.loc[8, [2022, 2023, 2024]] + east_empl.loc[15, [2022, 2023, 2024]]
east_empl.loc[18, [2022, 2023, 2024]] = east_empl.loc[18, [2022, 2023, 2024]] + east_empl.loc[3, [2022, 2023, 2024]]
east_empl = east_empl.drop([3, 15]).reset_index(drop=True)

In [32]:
east_empl_22_24 = east_empl.melt(id_vars='rayon', value_vars=[2022, 2023, 2024], var_name='year', value_name='employment')

### 2014-2021

In [33]:
ek_empl = pd.read_excel("../Data/Employment/East-Kazakhstan.xlsx", skiprows=30, nrows=20, header=None, usecols='A, F:I', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [34]:
ek_empl.columns = ['rayon', 2018, 2019, 2020, 2021]

rayons = ['Oskemen_city', 'Kurchatov_city', 'Ridder_city', 'Semey_city', 'Abay', 'Ayagoz', 'Beskaragay', 'Boroduliha', 'Glubokoe', 'Zharma', 'Zaysan', 'Altay', 'Kokpekti', 'Kurshim', 'Katonkaragay', 'Tarbagatay', 'Ulan', 'Urzhar', 'Shemonaiha']

ek_empl['rayon'] = rayons

for i in [2018, 2019, 2020, 2021]:
    ek_empl[i] = ek_empl[i].astype(float)

In [35]:
east_empl_18_21 = ek_empl.melt(id_vars='rayon', value_vars=[2018, 2019, 2020, 2021], var_name='year', value_name='employment')

In [36]:
east_empl = pd.concat([east_empl_18_21, east_empl_22_24], ignore_index=True)
east_empl

              rayon  year  employment
0      Oskemen_city  2018       168.7
1    Kurchatov_city  2018         7.0
2       Ridder_city  2018        29.7
3        Semey_city  2018       165.3
4              Abay  2018         6.8
..              ...   ...         ...
128         Kurshim  2024        10.5
129    Katonkaragay  2024        10.3
130      Tarbagatay  2024        18.1
131            Ulan  2024        17.2
132      Shemonaiha  2024        20.8

[133 rows x 3 columns]

## Other controls

In [37]:
kurchatov = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="моног.Курчатов", header=2, usecols='B, AD:AJ', nrows=272, na_values=['x', 'х', '-', '', ' ', '...'])

In [38]:
kurchatov.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kurchatov = kurchatov.loc[[134, 167, 257]].reset_index(drop=True)

In [39]:
kurchatov['Indicator'] = ['production', 'agriculture', 'retail']
kurchatov[2024] = kurchatov[2024].str.replace(',', '.')
kurchatov[2024] = kurchatov[2024].str.replace(')', '')
kurchatov[2024] = kurchatov[2024].str.replace(' ', '')
kurchatov[2024] = kurchatov[2024].astype(float)

In [40]:
kurchatov = pd.melt(kurchatov, id_vars=['Indicator'], var_name='year', value_name='value')
kurchatov = kurchatov.pivot(index='year', columns='Indicator', values='value').reset_index()
kurchatov.insert(0, 'rayon', 'Kurchatov_city')
kurchatov.columns.name = None

In [41]:
semey = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Семей", header=2, usecols='A, AC:AI', nrows=229, na_values=['x', 'х', '-', '', ' ', '...'])

In [42]:
semey.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
semey = semey.loc[[117, 149, 218]].reset_index(drop=True)

In [43]:
semey['Indicator'] = ['production', 'agriculture', 'retail']
semey[2024] = semey[2024].str.replace(',', '.')
semey[2024] = semey[2024].str.replace(')', '')
semey[2024] = semey[2024].str.replace(' ', '')
semey[2024] = semey[2024].astype(float)

In [44]:
zh_semey = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Жаңасемей", header=4, usecols='A:B', nrows=229, na_values=['x', 'х', '-', '', ' ', '...'])

In [45]:
zh_semey.columns = ['Indicator', 2024]
zh_semey = zh_semey.loc[[117, 149, 218]].reset_index(drop=True)

In [46]:
zh_semey['Indicator'] = ['production', 'agriculture', 'retail']
zh_semey[2024] = zh_semey[2024].replace(zh_semey[2024].iloc[2], '1.8')
zh_semey[2024] = zh_semey[2024].str.replace(' ', '')
zh_semey[2024] = zh_semey[2024].str.replace(',', '.')
zh_semey[2024] = zh_semey[2024].str.replace(')', '')
zh_semey[2024] = zh_semey[2024].astype(float)

In [47]:
semey[2024] = semey[2024] + zh_semey[2024]

In [48]:
semey = pd.melt(semey, id_vars=['Indicator'], var_name='year', value_name='value')
semey = semey.pivot(index='year', columns='Indicator', values='value').reset_index()
semey.insert(0, 'rayon', 'Semey_city')
semey.columns.name = None

In [49]:
abay = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Абай", header=3, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [50]:
abay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
abay = abay.loc[[117, 149, 218]].reset_index(drop=True)

In [51]:
abay['Indicator'] = ['production', 'agriculture', 'retail']
abay[2024] = abay[2024].str.replace(',', '.')
abay[2024] = abay[2024].str.replace(')', '')
abay[2024] = abay[2024].str.replace(' ', '')
abay[2024] = abay[2024].astype(float)

In [52]:
abay = pd.melt(abay, id_vars=['Indicator'], var_name='year', value_name='value')
abay = abay.pivot(index='year', columns='Indicator', values='value').reset_index()
abay.insert(0, 'rayon', 'Abay')
abay.columns.name = None

In [53]:
ayagoz = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Аягоз", header=2, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [54]:
ayagoz.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
ayagoz = ayagoz.loc[[117, 149, 218]].reset_index(drop=True)

In [55]:
ayagoz['Indicator'] = ['production', 'agriculture', 'retail']
ayagoz[2024] = ayagoz[2024].str.replace(',', '.')
ayagoz[2024] = ayagoz[2024].str.replace(')', '')
ayagoz[2024] = ayagoz[2024].str.replace(' ', '')
ayagoz[2024] = ayagoz[2024].astype(float)

In [56]:
ayagoz = pd.melt(ayagoz, id_vars=['Indicator'], var_name='year', value_name='value')
ayagoz = ayagoz.pivot(index='year', columns='Indicator', values='value').reset_index()
ayagoz.insert(0, 'rayon', 'Ayagoz')
ayagoz.columns.name = None

In [57]:
beskaragay = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Бескарагай", header=4, usecols='A, AC:AI', nrows=232, na_values=['x', 'х', '-', '', ' ', '...'])

In [58]:
beskaragay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
beskaragay = beskaragay.loc[[119, 151, 220]].reset_index(drop=True)

In [59]:
beskaragay['Indicator'] = ['production', 'agriculture', 'retail']
beskaragay[2024] = beskaragay[2024].str.replace(',', '.')
beskaragay[2024] = beskaragay[2024].str.replace(')', '')
beskaragay[2024] = beskaragay[2024].str.replace(' ', '')
beskaragay[2024] = beskaragay[2024].astype(float)

In [60]:
beskaragay = pd.melt(beskaragay, id_vars=['Indicator'], var_name='year', value_name='value')
beskaragay = beskaragay.pivot(index='year', columns='Indicator', values='value').reset_index()
beskaragay.insert(0, 'rayon', 'Beskaragay')
beskaragay.columns.name = None

In [61]:
boroduliha = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Бородулиха", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [62]:
boroduliha.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
boroduliha = boroduliha.loc[[117, 149, 218]].reset_index(drop=True)

In [63]:
boroduliha['Indicator'] = ['production', 'agriculture', 'retail']
boroduliha[2024] = boroduliha[2024].str.replace(',', '.')
boroduliha[2024] = boroduliha[2024].str.replace(')', '')
boroduliha[2024] = boroduliha[2024].str.replace(' ', '')
boroduliha[2024] = boroduliha[2024].astype(float)

In [64]:
boroduliha = pd.melt(boroduliha, id_vars=['Indicator'], var_name='year', value_name='value')
boroduliha = boroduliha.pivot(index='year', columns='Indicator', values='value').reset_index()
boroduliha.insert(0, 'rayon', 'Boroduliha')
boroduliha.columns.name = None

In [65]:
zharma = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Жарма", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [66]:
zharma.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
zharma = zharma.loc[[117, 149, 218]].reset_index(drop=True)

In [67]:
zharma['Indicator'] = ['production', 'agriculture', 'retail']
zharma[2024] = zharma[2024].str.replace(',', '.')
zharma[2024] = zharma[2024].str.replace(')', '')
zharma[2024] = zharma[2024].str.replace(' ', '')
zharma[2024] = zharma[2024].astype(float)

In [68]:
zharma = pd.melt(zharma, id_vars=['Indicator'], var_name='year', value_name='value')
zharma = zharma.pivot(index='year', columns='Indicator', values='value').reset_index()
zharma.insert(0, 'rayon', 'Zharma')
zharma.columns.name = None

In [69]:
kokpekti = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Кокпекты", header=4, usecols='A, AC:AI', nrows=232, na_values=['x', 'х', '-', '', ' ', '...'])

In [70]:
kokpekti.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
kokpekti = kokpekti.loc[[119, 151, 220]].reset_index(drop=True)

In [71]:
kokpekti['Indicator'] = ['production', 'agriculture', 'retail']
kokpekti[2024] = kokpekti[2024].str.replace(',', '.')
kokpekti[2024] = kokpekti[2024].str.replace(')', '')
kokpekti[2024] = kokpekti[2024].str.replace(' ', '')
kokpekti[2024] = kokpekti[2024].astype(float)

In [72]:
aksuat = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Аксуат", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [73]:
aksuat.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
aksuat = aksuat.loc[[117, 149, 218]].reset_index(drop=True)

In [74]:
aksuat['Indicator'] = ['production', 'agriculture', 'retail']
aksuat[2024] = aksuat[2024].str.replace(',', '.')
aksuat[2024] = aksuat[2024].str.replace(')', '')
aksuat[2024] = aksuat[2024].str.replace(' ', '')
aksuat[2024] = aksuat[2024].astype(float)

In [75]:
urzhar = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Урджар", header=4, usecols='A, AC:AI', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [76]:
urzhar.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023, 2024]
urzhar = urzhar.loc[[117, 149, 218]].reset_index(drop=True)

In [77]:
urzhar['Indicator'] = ['production', 'agriculture', 'retail']
urzhar[2024] = urzhar[2024].str.replace(',', '.')
urzhar[2024] = urzhar[2024].str.replace(')', '')
urzhar[2024] = urzhar[2024].str.replace(' ', '')
urzhar[2024] = urzhar[2024].astype(float)

In [78]:
makanshi = pd.read_excel("../Data/Controls/Abay_All.xls", sheet_name="Мақаншы", header=4, usecols='A:B', nrows=230, na_values=['x', 'х', '-', '', ' ', '...'])

In [79]:
makanshi.columns = ['Indicator', 2024]
makanshi = makanshi.loc[[117, 149, 218]].reset_index(drop=True)

In [80]:
makanshi['Indicator'] = ['production', 'agriculture', 'retail']
makanshi[2024] = makanshi[2024].str.replace(',', '.')
makanshi[2024] = makanshi[2024].str.replace(')', '')
makanshi[2024] = makanshi[2024].str.replace(' ', '')
makanshi[2024] = makanshi[2024].astype(float)

In [81]:
urzhar[2024] = urzhar[2024] + makanshi[2024]

In [82]:
urzhar = pd.melt(urzhar, id_vars=['Indicator'], var_name='year', value_name='value')
urzhar = urzhar.pivot(index='year', columns='Indicator', values='value').reset_index()
urzhar.insert(0, 'rayon', 'Urzhar')
urzhar.columns.name = None

In [83]:
oskemen = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="У-ка", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [84]:
oskemen.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
oskemen = oskemen.loc[[125, 157, 226]].reset_index(drop=True)
oskemen['Indicator'] = ['production', 'agriculture', 'retail']

In [85]:
oskemen = pd.melt(oskemen, id_vars=['Indicator'], var_name='year', value_name='value')
oskemen = oskemen.pivot(index='year', columns='Indicator', values='value').reset_index()
oskemen.insert(0, 'rayon', 'Oskemen_city')
oskemen.columns.name = None

In [86]:
ridder = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Риддер", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [87]:
ridder.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ridder = ridder.loc[[125, 157, 226]].reset_index(drop=True)
ridder['Indicator'] = ['production', 'agriculture', 'retail']

In [88]:
ridder_city = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Моногорода Риддер", header=1, usecols='B, K:P', nrows=279, na_values=['x', 'х', '-', '', ' ', '...'])

In [89]:
ridder_city.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ridder_city = ridder_city.loc[[137, 172, 263]].reset_index(drop=True)
ridder_city['Indicator'] = ['production', 'agriculture', 'retail']

In [90]:
ridder_city[[2018, 2019, 2020, 2021, 2022, 2023]] = ridder_city[[2018, 2019, 2020, 2021, 2022, 2023]] + ridder[[2018, 2019, 2020, 2021, 2022, 2023]]

In [91]:
ridder_city = pd.melt(ridder_city, id_vars=['Indicator'], var_name='year', value_name='value')
ridder_city = ridder_city.pivot(index='year', columns='Indicator', values='value').reset_index()
ridder_city.insert(0, 'rayon', 'Ridder_city')
ridder_city.columns.name = None

In [92]:
glubokoe = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Глубокое", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [93]:
glubokoe.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
glubokoe = glubokoe.loc[[125, 157, 226]].reset_index(drop=True)
glubokoe['Indicator'] = ['production', 'agriculture', 'retail']

In [94]:
glubokoe = pd.melt(glubokoe, id_vars=['Indicator'], var_name='year', value_name='value')
glubokoe = glubokoe.pivot(index='year', columns='Indicator', values='value').reset_index()
glubokoe.insert(0, 'rayon', 'Glubokoe')
glubokoe.columns.name = None

In [95]:
zaysan = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Зайсан", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [96]:
zaysan.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
zaysan = zaysan.loc[[125, 157, 226]].reset_index(drop=True)
zaysan['Indicator'] = ['production', 'agriculture', 'retail']

In [97]:
zaysan = pd.melt(zaysan, id_vars=['Indicator'], var_name='year', value_name='value')
zaysan = zaysan.pivot(index='year', columns='Indicator', values='value').reset_index()
zaysan.insert(0, 'rayon', 'Zaysan')
zaysan.columns.name = None

In [98]:
altay = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Алтай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [99]:
altay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
altay = altay.loc[[125, 157, 226]].reset_index(drop=True)
altay['Indicator'] = ['production', 'agriculture', 'retail']

In [100]:
altay_city = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Моногорода Алтай", header=1, usecols='B, K:P', nrows=278, na_values=['x', 'х', '-', '', ' ', '...', '…'])

In [101]:
altay_city.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
altay_city = altay_city.loc[[137, 172, 263]].reset_index(drop=True)
altay_city['Indicator'] = ['production', 'agriculture', 'retail']

In [102]:
altay[[2018, 2019, 2020, 2021, 2022, 2023]] = altay[[2018, 2019, 2020, 2021, 2022, 2023]] + altay_city[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2740354433.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  altay[[2018, 2019, 2020, 2021, 2022, 2023]] = altay[[2018, 2019, 2020, 2021, 2022, 2023]] + altay_city[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [103]:
altay = pd.melt(altay, id_vars=['Indicator'], var_name='year', value_name='value')
altay = altay.pivot(index='year', columns='Indicator', values='value').reset_index()
altay.insert(0, 'rayon', 'Altay')
altay.columns.name = None

In [104]:
kurshim = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Курчум", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [105]:
kurshim.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
kurshim = kurshim.loc[[125, 157, 226]].reset_index(drop=True)
kurshim['Indicator'] = ['production', 'agriculture', 'retail']

In [106]:
kurshim = pd.melt(kurshim, id_vars=['Indicator'], var_name='year', value_name='value')
kurshim = kurshim.pivot(index='year', columns='Indicator', values='value').reset_index()
kurshim.insert(0, 'rayon', 'Kurshim')
kurshim.columns.name = None

In [107]:
katon = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Катон-Карагай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [108]:
katon.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
katon = katon.loc[[125, 157, 226]].reset_index(drop=True)
katon['Indicator'] = ['production', 'agriculture', 'retail']

In [109]:
katon = pd.melt(katon, id_vars=['Indicator'], var_name='year', value_name='value')
katon = katon.pivot(index='year', columns='Indicator', values='value').reset_index()
katon.insert(0, 'rayon', 'Katonkaragay')
katon.columns.name = None

In [110]:
samar = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Самар", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [111]:
samar.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
samar = samar.loc[[125, 157, 226]].reset_index(drop=True)
samar['Indicator'] = ['production', 'agriculture', 'retail']

In [112]:
kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] = kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] + samar[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/3062827892.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] = kokpekti[[2018, 2019, 2020, 2021, 2022, 2023]] + samar[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [113]:
kokpekti = pd.melt(kokpekti, id_vars=['Indicator'], var_name='year', value_name='value')
kokpekti = kokpekti.pivot(index='year', columns='Indicator', values='value').reset_index()
kokpekti.insert(0, 'rayon', 'Kokpekti')
kokpekti.columns.name = None

In [114]:
tarbagatay = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Тарбагатай", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [115]:
tarbagatay.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
tarbagatay = tarbagatay.loc[[125, 157, 226]].reset_index(drop=True)
tarbagatay['Indicator'] = ['production', 'agriculture', 'retail']

In [116]:
tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] = tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] + aksuat[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/3275713407.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] = tarbagatay[[2018, 2019, 2020, 2021, 2022, 2023]] + aksuat[[2018, 2019, 2020, 2021, 2022, 2023]].fillna(0)

In [117]:
tarbagatay = pd.melt(tarbagatay, id_vars=['Indicator'], var_name='year', value_name='value')
tarbagatay = tarbagatay.pivot(index='year', columns='Indicator', values='value').reset_index()
tarbagatay.insert(0, 'rayon', 'Tarbagatay')
tarbagatay.columns.name = None

In [118]:
ulan = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Улан", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [119]:
ulan.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
ulan = ulan.loc[[125, 157, 226]].reset_index(drop=True)
ulan['Indicator'] = ['production', 'agriculture', 'retail']

In [120]:
ulan = pd.melt(ulan, id_vars=['Indicator'], var_name='year', value_name='value')
ulan = ulan.pivot(index='year', columns='Indicator', values='value').reset_index()
ulan.insert(0, 'rayon', 'Ulan')
ulan.columns.name = None

In [121]:
shemonaiha = pd.read_excel("../Data/Controls/East-Kazakhstan_All.xls", sheet_name="Шемонаиха", header=4, usecols='A, AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [122]:
shemonaiha.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
shemonaiha = shemonaiha.loc[[125, 157, 226]].reset_index(drop=True)
shemonaiha['Indicator'] = ['production', 'agriculture', 'retail']

In [123]:
shemonaiha = pd.melt(shemonaiha, id_vars=['Indicator'], var_name='year', value_name='value')
shemonaiha = shemonaiha.pivot(index='year', columns='Indicator', values='value').reset_index()
shemonaiha.insert(0, 'rayon', 'Shemonaiha')
shemonaiha.columns.name = None

In [124]:
east_controls = pd.concat([oskemen, kurchatov, ridder_city, semey, abay, ayagoz, beskaragay, boroduliha, glubokoe, zharma, zaysan, altay, kokpekti, kurshim, katon, tarbagatay, ulan, urzhar, shemonaiha], ignore_index=True)

In [125]:
east_controls

            rayon  year agriculture   production    retail
0    Oskemen_city  2018     18710.2    1089708.7    505623
1    Oskemen_city  2019     20500.4      1188598  575488.1
2    Oskemen_city  2020     26403.4    1267686.2  614110.3
3    Oskemen_city  2021       33072    1432273.9  710753.9
4    Oskemen_city  2022     29324.4  1680829.586  856099.9
..            ...   ...         ...          ...       ...
118    Shemonaiha  2019     33198.3      64098.8   10808.9
119    Shemonaiha  2020     35344.6      74754.4   11599.3
120    Shemonaiha  2021     54787.5      92854.4   13944.5
121    Shemonaiha  2022     60296.4   118102.441   17349.8
122    Shemonaiha  2023     51963.6    122014.43   19931.9

[123 rows x 5 columns]

## PPI

In [126]:
east_ppi = pd.read_excel("../Data/PPI/East-Kazakhstan.xls", header=4, usecols='AC:AH', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

In [127]:
east_ppi.columns = [2018, 2019, 2020, 2021, 2022, 2023]
east_ppi = east_ppi.loc[80].reset_index(drop=True)
east_ppi.loc[[0, 1, 2, 3, 5]] = ['100.7', '103.4', '121.1', '116.6', '101.5']
east_ppi = east_ppi.str.replace(',', '.').astype(float)

In [128]:
rayons = list(east_inv['rayon'].unique())

In [129]:
dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2018, 2024),
        'ppi': east_ppi.values
    })
    dfs.append(df_temp)

east_ppi = pd.concat(dfs, ignore_index=True)

In [130]:
east_ppi

            rayon  year    ppi
0    Oskemen_city  2018  100.7
1    Oskemen_city  2019  103.4
2    Oskemen_city  2020  121.1
3    Oskemen_city  2021  116.6
4    Oskemen_city  2022  101.9
..            ...   ...    ...
109    Shemonaiha  2019  103.4
110    Shemonaiha  2020  121.1
111    Shemonaiha  2021  116.6
112    Shemonaiha  2022  101.9
113    Shemonaiha  2023  101.5

[114 rows x 3 columns]

## Combine together

In [131]:
dfs = [east_inv, east_empl, east_controls, east_ppi]

east_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

east_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Abay,2868180,3092.0,3092.0,981955.0,East-Kazakhstan,2018,6.8,22795.4,1593.9,1869.4,100.7
1,Abay,2514048,405350.0,67923.0,529073.0,East-Kazakhstan,2019,6.8,25865.6,2352.1,2470.9,103.4
2,Abay,7040473,5593.0,5593.0,784053.0,East-Kazakhstan,2020,6.7,29614.9,3201.9,2720.2,121.1
3,Abay,3671620,1643.0,1643.0,1125547.0,East-Kazakhstan,2021,6.8,34162.9,5753.1,3228.1,116.6
4,Abay,6258213,0.0,0.0,1723622.0,East-Kazakhstan,2022,7.0,40779.1,7437.8,4868.6,101.9
...,...,...,...,...,...,...,...,...,...,...,...,...
128,Zharma,8965750,30650877.0,22714979.0,2663341.0,East-Kazakhstan,2020,16.9,29248.6,319768.5,14468.2,121.1
129,Zharma,11089448,16530654.0,5231374.0,7488723.0,East-Kazakhstan,2021,16.9,34225.4,294781.8,16452.7,116.6
130,Zharma,22694539,28933370.0,17497704.0,17646057.0,East-Kazakhstan,2022,18.8,42371.9,282815.6,21264.1,101.9
131,Zharma,57603107,17378503.0,5777877.0,23491273.0,East-Kazakhstan,2023,17.8,41639.4,315236,31105.3,101.5
132,Zharma,25006215,44066611.0,31108924.0,11218226.0,East-Kazakhstan,2024,17.0,NaN,398951.97,34366.87,NaN

# Almaty oblast and Zhetisu oblast

## Investments

### 2022-2024

In [132]:
zhetisu_all_2022 = pd.read_excel("../Data/Investments/Zhetisu/2022_Investments.xls", sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_all_2023 = pd.read_excel("../Data/Investments/Zhetisu/2023_Investments.xlsx", sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_all_2024 = pd.read_excel("../Data/Investments/Zhetisu/2024_Investments.xls", sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

zhetisu_non_2022 = pd.read_excel("../Data/Investments/Zhetisu/2022_Investments.xls", sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_non_2023 = pd.read_excel("../Data/Investments/Zhetisu/2023_Investments.xlsx", sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
zhetisu_non_2024 = pd.read_excel("../Data/Investments/Zhetisu/2024_Investments.xls", sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [133]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [zhetisu_all_2022, zhetisu_all_2023, zhetisu_all_2024]:
    df.columns = all_columns

for df in [zhetisu_non_2022, zhetisu_non_2023, zhetisu_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Taldykorgan_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Yeskeldi', 'Kerbulak', 'Koksu', 'Karatal', 'Panfilov', 'Sarkan']

for df in [zhetisu_all_2022, zhetisu_all_2023, zhetisu_all_2024, zhetisu_non_2022, zhetisu_non_2023, zhetisu_non_2024]:
    df['rayon'] = rayon_names

zhetisu_2022 = zhetisu_all_2022.merge(zhetisu_non_2022, on='rayon')
zhetisu_2023 = zhetisu_all_2023.merge(zhetisu_non_2023, on='rayon')
zhetisu_2024 = zhetisu_all_2024.merge(zhetisu_non_2024, on='rayon')

dfs = [zhetisu_2022, zhetisu_2023, zhetisu_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [134]:
almaty_all_2022 = pd.read_excel("../Data/Investments/Almaty/2022_Investments.xls", sheet_name='13', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_all_2023 = pd.read_excel("../Data/Investments/Almaty/2023_Investments.xlsx", sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_all_2024 = pd.read_excel("../Data/Investments/Almaty/2024_Investments.xls", sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

almaty_non_2022 = pd.read_excel("../Data/Investments/Almaty/2022_Investments.xls", sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_non_2023 = pd.read_excel("../Data/Investments/Almaty/2023_Investments.xlsx", sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_non_2024 = pd.read_excel("../Data/Investments/Almaty/2024_Investments.xls", sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [135]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [almaty_all_2022, almaty_all_2023, almaty_all_2024]:
    df.columns = all_columns

for df in [almaty_non_2022, almaty_non_2023, almaty_non_2024]:
    df.columns = non_columns
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

almaty_non_2022 = almaty_non_2022.loc[:9]

rayon_names = ['Konayev_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']
rayon_names_2024 = ['Konayev_city', 'Alatau_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']

dfs = [almaty_all_2022, almaty_all_2023, almaty_all_2024, almaty_non_2022, almaty_non_2023, almaty_non_2024]

for i in range(6):
    df = dfs[i]
    if (i == 2) | (i == 5):
        df['rayon'] = rayon_names_2024
    else:
        df['rayon'] = rayon_names

alm_2022 = almaty_all_2022.merge(almaty_non_2022, on='rayon')
alm_2023 = almaty_all_2023.merge(almaty_non_2023, on='rayon')
alm_2024 = almaty_all_2024.merge(almaty_non_2024, on='rayon')

alm_2022.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2022.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2022.loc[4, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
alm_2023.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2023.loc[6, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2023.loc[4, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
alm_2024.loc[7, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = alm_2024.loc[7, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + alm_2024.loc[5, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]

alm_2022 = alm_2022.drop(4).reset_index(drop=True)
alm_2023 = alm_2023.drop(4).reset_index(drop=True)
alm_2024 = alm_2024.drop(5).reset_index(drop=True)

dfs = [alm_2022, alm_2023, alm_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

almaty_2022 = pd.concat([zhetisu_2022, alm_2022], ignore_index=True)
almaty_2023 = pd.concat([zhetisu_2023, alm_2023], ignore_index=True)
almaty_2024 = pd.concat([zhetisu_2024, alm_2024], ignore_index=True)

### 2016 - 2021

In [136]:
almaty_all_2016 = pd.read_excel("../Data/Investments/Almaty/2016_Investments/Internal_vs_external.xls", header=6, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2016 = pd.read_excel("../Data/Investments/Almaty/2016_Investments/Greenfield_investments.xls", header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:18]

almaty_all_2017 = pd.read_excel("../Data/Investments/Almaty/2017_Investments/Internal_vs_external.xls", header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2017 = pd.read_excel("../Data/Investments/Almaty/2017_Investments/Greenfield_investments.xls", header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:18]

almaty_all_2018 = pd.read_excel("../Data/Investments/Almaty/2018_Investments/Internal_vs_external.xls", header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2018 = pd.read_excel("../Data/Investments/Almaty/2018_Investments/Greenfield_investments.xlsx", header=5, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2019 = pd.read_excel("../Data/Investments/Almaty/2019_Investments.xls", sheet_name='14.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2019 = pd.read_excel("../Data/Investments/Almaty/2019_Investments.xls", sheet_name='15.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2020 = pd.read_excel("../Data/Investments/Almaty/2020_Investments.xls", sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2020 = pd.read_excel("../Data/Investments/Almaty/2020_Investments.xls", sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True).loc[:19]

almaty_all_2021 = pd.read_excel("../Data/Investments/Almaty/2021_Investments.xls", sheet_name='13.', header=5, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
almaty_nonextr_2021 = pd.read_excel("../Data/Investments/Almaty/2021_Investments.xls", sheet_name='14.', header=6, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [137]:
rayons_2016 = ['Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Yeskeldi', 'Zhambyl', 'Ile', 'Karasay', 'Karatal', 'Kerbulak', 'Koksu', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Uyghur', 'Konayev_city', 'Taldykorgan_city', 'Tekeli_city']
rayons_2017 = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']
rayons = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']

all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']


dfs = [almaty_all_2016, almaty_all_2017, almaty_all_2018, almaty_all_2019, almaty_all_2020, almaty_all_2021]
for i in range(6):
    df = dfs[i]
    df.columns = all_columns
    if i == 0:
        df['rayon'] = rayons_2016
    elif i == 1:
        df['rayon'] = rayons_2017
    else:
        df['rayon'] = rayons

dfs = [almaty_nonextr_2016, almaty_nonextr_2017, almaty_nonextr_2018, almaty_nonextr_2019, almaty_nonextr_2020, almaty_nonextr_2021]
for i in range(6):
    df = dfs[i]
    df.columns = non_columns
    if i == 0:
        df['rayon'] = rayons_2016
    elif i == 1:
        df['rayon'] = rayons_2017
    else:
        df['rayon'] = rayons
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

almaty_2016 = almaty_all_2019.merge(almaty_nonextr_2016, on='rayon')
almaty_2017 = almaty_all_2019.merge(almaty_nonextr_2017, on='rayon')
almaty_2018 = almaty_all_2019.merge(almaty_nonextr_2018, on='rayon')
almaty_2019 = almaty_all_2019.merge(almaty_nonextr_2019, on='rayon')
almaty_2020 = almaty_all_2020.merge(almaty_nonextr_2020, on='rayon')
almaty_2021 = almaty_all_2021.merge(almaty_nonextr_2021, on='rayon')


dfs = [almaty_2018, almaty_2019, almaty_2020, almaty_2021]
for i in range(4):
    df = dfs[i]
    df.loc[14, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] = df.loc[14, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']] + df.loc[8, ['l_all_inv', 'f_all_inv', 'f_nonextr_inv', 'l_nonextr_inv']]
    df.drop(8, inplace=True)
    df.reset_index(drop=True, inplace=True)


dfs = [almaty_2016, almaty_2017, almaty_2018, almaty_2019, almaty_2020, almaty_2021]

for i in range(6):
    df = dfs[i]
    df['oblast'] = 'Almaty'
    if i == 0:
        df['year'] = 2016
    elif i == 1:
        df['year'] = 2017
    elif i == 2:
        df['year'] = 2018
    elif i == 3:
        df['year'] = 2019
    elif i == 4:
        df['year'] = 2020
    else:
        df['year'] = 2021


almaty_inv = pd.concat([almaty_2016, almaty_2017, almaty_2018, almaty_2019, almaty_2020, almaty_2021, almaty_2022, almaty_2023, almaty_2024], ignore_index=True)
almaty_inv

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Taldykorgan_city,65339638.0,1102849.0,376759,30557091.0,Almaty,2016
1,Konayev_city,13587573.0,20825309.0,2526031,6433220.0,Almaty,2016
2,Tekeli_city,5188744.0,987100.0,56235,3584210.0,Almaty,2016
3,Aksu,12974898.0,115616.0,21135,338507.0,Almaty,2016
4,Alakol,27590611.0,1432693.0,639604,12909596.0,Almaty,2016
...,...,...,...,...,...,...,...
167,Karasay,172344338.0,51895433.0,51895433.0,111379415.0,Almaty,2024
168,Rayimbek,22816202.0,0.0,0.0,8753487.0,Almaty,2024
169,Talgar,105091760.0,19530203.0,19530203.0,79502676.0,Almaty,2024
170,Uyghur,14859311.0,10419128.0,2744199.0,4466472.0,Almaty,2024
171,Ile,145558420.0,59945415.0,59945415.0,121898606.0,Almaty,2024

## Employment

### 2022-2023

In [138]:
zhetisu_empl = pd.read_excel("../Data/Employment/Zhetisu.xlsx", skiprows=21, nrows=10, header=None, usecols='A:C')
alm_empl = pd.read_excel("../Data/Employment/Almaty.xlsx", skiprows=31, nrows=20, header=None, usecols='A, J:K', na_values=['x', 'х', '-', '', ' ']).dropna().reset_index(drop=True)

In [139]:
zhetisu_empl.columns = ['rayon', 2022, 2023]

rayons = ['Taldykorgan_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Yeskeldi', 'Kerbulak', 'Koksu', 'Karatal', 'Panfilov', 'Sarkan']

zhetisu_empl['rayon'] = rayons

zhetisu_empl[2022] = zhetisu_empl[2022].astype(float)
zhetisu_empl[2023] = zhetisu_empl[2023].astype(float)

alm_empl.columns = ['rayon', 2022, 2023]

rayons = ['Konayev_city', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Karasay', 'Rayimbek', 'Talgar', 'Uyghur', 'Ile']

alm_empl['rayon'] = rayons

alm_empl[2022] = alm_empl[2022].astype(float)
alm_empl[2023] = alm_empl[2023].astype(float)

almaty_empl = pd.concat([zhetisu_empl, alm_empl], ignore_index=True)

almaty_empl.loc[16, [2022, 2023]] = almaty_empl.loc[16, [2022, 2023]] + almaty_empl.loc[14, [2022, 2023]]
almaty_empl = almaty_empl.drop(14).reset_index(drop=True)

almaty_empl_22_23 = almaty_empl.melt(id_vars='rayon', value_vars=[2022, 2023], var_name='year', value_name='employment')

### 2016-2021

In [140]:
alm_empl = pd.read_excel("../Data/Employment/Almaty.xlsx", skiprows=31, nrows=20, header=None, usecols='A, D:I', na_values=['x', 'х', '-', '', ' ']).fillna(0).reset_index(drop=True)
alm_empl

                   0      3      4      5      6      7      8
0   г.а. Талдыкорган   85.3   86.3   86.8   88.5   86.3   88.5
1        г.а. Конаев   31.6   31.1   31.7   31.1   29.3   28.5
2        г.а. Текели   16.6   17.6   17.7   17.5   17.2   17.2
3          Аксуский    18.9   18.9   18.1   18.1   17.4   17.2
4       Алакольский    35.1   35.1   35.0   34.2   33.3   31.9
5         Балхашский   14.7   14.6   14.4   14.5   14.1   13.9
6   Енбекшиказахский  157.9  156.3  157.9  152.2  147.9  147.2
7         Жамбылский   75.0   78.4   79.9   81.9   81.3   81.1
8          Кегенский    0.0    0.0   15.5   14.9   14.6   14.3
9       Кербулакский   24.2   23.9   23.4   23.1   22.0   21.5
10         Коксуский   21.6   21.0   20.9   20.2   19.5   19.7
11      Каратальский   24.2   23.8   22.9   23.0   22.6   21.1
12       Карасайский  113.4  120.4  125.8  128.1  129.0  130.0
13      Панфиловский   61.5   61.5   61.3   61.2   58.4   59.2
14      Райымбекский   41.7   38.4   22.3   19.9   19.4   18.3
15       Саркандский   20.3   19.1   18.5   17.4   16.5   15.7
16        Талгарский   93.2   93.8   94.0   97.2   96.6   97.9
17     Ескельдинский   23.8   23.6   23.0   22.1   21.4   21.0
18         Уйгурский   32.2   31.1   30.6   30.0   28.9   28.8
19          Илийский   94.2   93.2   94.5   95.6   98.3   99.9

In [141]:
alm_empl.columns = ['rayon', 2016, 2017, 2018, 2019, 2020, 2021]

rayons = ['Taldykorgan_city', 'Konayev_city', 'Tekeli_city', 'Aksu', 'Alakol', 'Balkhash', 'Enbekshikazak', 'Zhambyl', 'Kegen', 'Kerbulak', 'Koksu', 'Karatal', 'Karasay', 'Panfilov', 'Rayimbek', 'Sarkan', 'Talgar', 'Yeskeldi', 'Uyghur', 'Ile']

alm_empl['rayon'] = rayons

for i in [2016, 2017, 2018, 2019, 2020, 2021]:
    alm_empl[i] = alm_empl[i].astype(float)

alm_empl.loc[14, [2016, 2017, 2018, 2019, 2020, 2021]] = alm_empl.loc[14, [2016, 2017, 2018, 2019, 2020, 2021]] + alm_empl.loc[8, [2016, 2017, 2018, 2019, 2020, 2021]]
alm_empl = alm_empl.drop(8).reset_index(drop=True)

alm_empl_16_21 = alm_empl.melt(id_vars='rayon', value_vars=[2016, 2017, 2018, 2019, 2020, 2021], var_name='year', value_name='employment')

almaty_empl = pd.concat([alm_empl_16_21, almaty_empl_22_23], ignore_index=True)
almaty_empl

                rayon  year  employment
0    Taldykorgan_city  2016        85.3
1        Konayev_city  2016        31.6
2         Tekeli_city  2016        16.6
3                Aksu  2016        18.9
4              Alakol  2016        35.1
..                ...   ...         ...
147           Karasay  2023       150.7
148          Rayimbek  2023        24.8
149            Talgar  2023       117.1
150            Uyghur  2023        28.2
151               Ile  2023       125.2

[152 rows x 3 columns]

## Other controls

In [142]:
taldykorgan = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="г.а.Талдыкорган", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

taldykorgan.columns = ['Indicator', 2022, 2023, 2024]
taldykorgan = taldykorgan.loc[[56, 77, 125]].reset_index(drop=True)

taldykorgan['Indicator'] = ['agriculture', 'production', 'retail']
taldykorgan[2024] = taldykorgan[2024].astype(str)
taldykorgan[2024] = taldykorgan[2024].str.replace(',', '.')
taldykorgan[2024] = taldykorgan[2024].str.replace(')', '')
taldykorgan[2024] = taldykorgan[2024].str.replace(' ', '')
taldykorgan[2024] = taldykorgan[2024].astype(float)

taldykorgan = pd.melt(taldykorgan, id_vars=['Indicator'], var_name='year', value_name='value')
taldykorgan = taldykorgan.pivot(index='year', columns='Indicator', values='value').reset_index()
taldykorgan.insert(0, 'rayon', 'Taldykorgan_city')
taldykorgan.columns.name = None

In [143]:
tekeli = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="г.а.Текели", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

tekeli.columns = ['Indicator', 2022, 2023, 2024]
tekeli = tekeli.loc[[56, 77, 125]].reset_index(drop=True)

tekeli['Indicator'] = ['agriculture', 'production', 'retail']
tekeli[2024] = tekeli[2024].astype(str)
tekeli[2024] = tekeli[2024].str.replace(',', '.')
tekeli[2024] = tekeli[2024].str.replace(')', '')
tekeli[2024] = tekeli[2024].str.replace(' ', '')
tekeli[2024] = tekeli[2024].astype(float)

tekeli = pd.melt(tekeli, id_vars=['Indicator'], var_name='year', value_name='value')
tekeli = tekeli.pivot(index='year', columns='Indicator', values='value').reset_index()
tekeli.insert(0, 'rayon', 'Tekeli_city')
tekeli.columns.name = None

In [144]:
aksu = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Аксуский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

aksu.columns = ['Indicator', 2022, 2023, 2024]
aksu = aksu.loc[[56, 77, 125]].reset_index(drop=True)

aksu['Indicator'] = ['agriculture', 'production', 'retail']
aksu[2024] = aksu[2024].astype(str)
aksu[2024] = aksu[2024].str.replace(',', '.')
aksu[2024] = aksu[2024].str.replace(')', '')
aksu[2024] = aksu[2024].str.replace(' ', '')
aksu[2024] = aksu[2024].astype(float)

aksu = pd.melt(aksu, id_vars=['Indicator'], var_name='year', value_name='value')
aksu = aksu.pivot(index='year', columns='Indicator', values='value').reset_index()
aksu.insert(0, 'rayon', 'Aksu')
aksu.columns.name = None

In [145]:
alakol = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Алакольский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

alakol.columns = ['Indicator', 2022, 2023, 2024]
alakol = alakol.loc[[56, 77, 125]].reset_index(drop=True)

alakol['Indicator'] = ['agriculture', 'production', 'retail']
alakol[2024] = alakol[2024].astype(str)
alakol[2024] = alakol[2024].str.replace(',', '.')
alakol[2024] = alakol[2024].str.replace(')', '')
alakol[2024] = alakol[2024].str.replace(' ', '')
alakol[2024] = alakol[2024].astype(float)

alakol = pd.melt(alakol, id_vars=['Indicator'], var_name='year', value_name='value')
alakol = alakol.pivot(index='year', columns='Indicator', values='value').reset_index()
alakol.insert(0, 'rayon', 'Alakol')
alakol.columns.name = None

In [146]:
kerbulak = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Кербулакский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

kerbulak.columns = ['Indicator', 2022, 2023, 2024]
kerbulak = kerbulak.loc[[56, 77, 125]].reset_index(drop=True)

kerbulak['Indicator'] = ['agriculture', 'production', 'retail']
kerbulak[2024] = kerbulak[2024].astype(str)
kerbulak[2024] = kerbulak[2024].str.replace(',', '.')
kerbulak[2024] = kerbulak[2024].str.replace(')', '')
kerbulak[2024] = kerbulak[2024].str.replace(' ', '')
kerbulak[2024] = kerbulak[2024].astype(float)

kerbulak = pd.melt(kerbulak, id_vars=['Indicator'], var_name='year', value_name='value')
kerbulak = kerbulak.pivot(index='year', columns='Indicator', values='value').reset_index()
kerbulak.insert(0, 'rayon', 'Kerbulak')
kerbulak.columns.name = None

In [147]:
koksu = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Коксуский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

koksu.columns = ['Indicator', 2022, 2023, 2024]
koksu = koksu.loc[[56, 77, 125]].reset_index(drop=True)

koksu['Indicator'] = ['agriculture', 'production', 'retail']
koksu[2024] = koksu[2024].astype(str)
koksu[2024] = koksu[2024].str.replace(',', '.')
koksu[2024] = koksu[2024].str.replace(')', '')
koksu[2024] = koksu[2024].str.replace(' ', '')
koksu[2024] = koksu[2024].astype(float)

koksu = pd.melt(koksu, id_vars=['Indicator'], var_name='year', value_name='value')
koksu = koksu.pivot(index='year', columns='Indicator', values='value').reset_index()
koksu.insert(0, 'rayon', 'Koksu')
koksu.columns.name = None

In [148]:
karatal = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Каратальский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

karatal.columns = ['Indicator', 2022, 2023, 2024]
karatal = karatal.loc[[56, 77, 125]].reset_index(drop=True)

karatal['Indicator'] = ['agriculture', 'production', 'retail']
karatal[2024] = karatal[2024].astype(str)
karatal[2024] = karatal[2024].str.replace(',', '.')
karatal[2024] = karatal[2024].str.replace(')', '')
karatal[2024] = karatal[2024].str.replace(' ', '')
karatal[2024] = karatal[2024].astype(float)

karatal = pd.melt(karatal, id_vars=['Indicator'], var_name='year', value_name='value')
karatal = karatal.pivot(index='year', columns='Indicator', values='value').reset_index()
karatal.insert(0, 'rayon', 'Karatal')
karatal.columns.name = None

In [149]:
panfilov = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Панфиловский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

panfilov.columns = ['Indicator', 2022, 2023, 2024]
panfilov = panfilov.loc[[56, 77, 125]].reset_index(drop=True)

panfilov['Indicator'] = ['agriculture', 'production', 'retail']
panfilov[2024] = panfilov[2024].astype(str)
panfilov[2024] = panfilov[2024].str.replace(',', '.')
panfilov[2024] = panfilov[2024].str.replace(')', '')
panfilov[2024] = panfilov[2024].str.replace(' ', '')
panfilov[2024] = panfilov[2024].astype(float)

panfilov = pd.melt(panfilov, id_vars=['Indicator'], var_name='year', value_name='value')
panfilov = panfilov.pivot(index='year', columns='Indicator', values='value').reset_index()
panfilov.insert(0, 'rayon', 'Panfilov')
panfilov.columns.name = None

In [150]:
sarkan = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Сарканский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

sarkan.columns = ['Indicator', 2022, 2023, 2024]
sarkan = sarkan.loc[[56, 77, 125]].reset_index(drop=True)

sarkan['Indicator'] = ['agriculture', 'production', 'retail']
sarkan[2024] = sarkan[2024].astype(str)
sarkan[2024] = sarkan[2024].str.replace(',', '.')
sarkan[2024] = sarkan[2024].str.replace(')', '')
sarkan[2024] = sarkan[2024].str.replace(' ', '')
sarkan[2024] = sarkan[2024].astype(float)

sarkan = pd.melt(sarkan, id_vars=['Indicator'], var_name='year', value_name='value')
sarkan = sarkan.pivot(index='year', columns='Indicator', values='value').reset_index()
sarkan.insert(0, 'rayon', 'Sarkan')
sarkan.columns.name = None

In [151]:
yeskeldi = pd.read_excel("../Data/Controls/Zhetisu_All.xls", sheet_name="Ескельдинский", header=3, usecols='B, C:E', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

yeskeldi.columns = ['Indicator', 2022, 2023, 2024]
yeskeldi = yeskeldi.loc[[56, 77, 125]].reset_index(drop=True)

yeskeldi['Indicator'] = ['agriculture', 'production', 'retail']
yeskeldi[2024] = yeskeldi[2024].astype(str)
yeskeldi[2024] = yeskeldi[2024].str.replace(',', '.')
yeskeldi[2024] = yeskeldi[2024].str.replace(')', '')
yeskeldi[2024] = yeskeldi[2024].str.replace(' ', '')
yeskeldi[2024] = yeskeldi[2024].astype(float)

yeskeldi = pd.melt(yeskeldi, id_vars=['Indicator'], var_name='year', value_name='value')
yeskeldi = yeskeldi.pivot(index='year', columns='Indicator', values='value').reset_index()
yeskeldi.insert(0, 'rayon', 'Yeskeldi')
yeskeldi.columns.name = None

In [152]:
konayev = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="г.а.Конаев", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

konayev.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
konayev = konayev.loc[[56, 77, 125]].reset_index(drop=True)

konayev['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    konayev[i] = konayev[i].astype(str)
    konayev[i] = konayev[i].str.replace(',', '.')
    konayev[i] = konayev[i].str.replace(')', '')
    konayev[i] = konayev[i].str.replace(' ', '')
    konayev[i] = konayev[i].str.replace('\xa0', '')
    konayev[i] = konayev[i].astype(float)

konayev = pd.melt(konayev, id_vars=['Indicator'], var_name='year', value_name='value')
konayev = konayev.pivot(index='year', columns='Indicator', values='value').reset_index()
konayev.insert(0, 'rayon', 'Konayev_city')
konayev.columns.name = None

In [153]:
balkhash = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Балхашский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

balkhash.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
balkhash = balkhash.loc[[56, 77, 125]].reset_index(drop=True)

balkhash['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    balkhash[i] = balkhash[i].astype(str)
    balkhash[i] = balkhash[i].str.replace(',', '.')
    balkhash[i] = balkhash[i].str.replace(')', '')
    balkhash[i] = balkhash[i].str.replace(' ', '')
    balkhash[i] = balkhash[i].str.replace('\xa0', '')
    balkhash[i] = balkhash[i].astype(float)

balkhash = pd.melt(balkhash, id_vars=['Indicator'], var_name='year', value_name='value')
balkhash = balkhash.pivot(index='year', columns='Indicator', values='value').reset_index()
balkhash.insert(0, 'rayon', 'Balkhash')
balkhash.columns.name = None

In [154]:
enbekshikazak = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Енбекшиказахский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

enbekshikazak.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
enbekshikazak = enbekshikazak.loc[[56, 77, 125]].reset_index(drop=True)

enbekshikazak['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    enbekshikazak[i] = enbekshikazak[i].astype(str)
    enbekshikazak[i] = enbekshikazak[i].str.replace(',', '.')
    enbekshikazak[i] = enbekshikazak[i].str.replace(')', '')
    enbekshikazak[i] = enbekshikazak[i].str.replace(' ', '')
    enbekshikazak[i] = enbekshikazak[i].str.replace('\xa0', '')
    enbekshikazak[i] = enbekshikazak[i].astype(float)

enbekshikazak = pd.melt(enbekshikazak, id_vars=['Indicator'], var_name='year', value_name='value')
enbekshikazak = enbekshikazak.pivot(index='year', columns='Indicator', values='value').reset_index()
enbekshikazak.insert(0, 'rayon', 'Enbekshikazak')
enbekshikazak.columns.name = None

In [155]:
zhambyl = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Жамбылский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

zhambyl.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
zhambyl = zhambyl.loc[[56, 77, 125]].reset_index(drop=True)

zhambyl['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    zhambyl[i] = zhambyl[i].astype(str)
    zhambyl[i] = zhambyl[i].str.replace(',', '.')
    zhambyl[i] = zhambyl[i].str.replace(')', '')
    zhambyl[i] = zhambyl[i].str.replace(' ', '')
    zhambyl[i] = zhambyl[i].str.replace('\xa0', '')
    zhambyl[i] = zhambyl[i].astype(float)

zhambyl = pd.melt(zhambyl, id_vars=['Indicator'], var_name='year', value_name='value')
zhambyl = zhambyl.pivot(index='year', columns='Indicator', values='value').reset_index()
zhambyl.insert(0, 'rayon', 'Zhambyl')
zhambyl.columns.name = None

In [156]:
kegen = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Кегенский", header=3, usecols='B, C:H', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

kegen.columns = ['Indicator', 2018, 2019, 2020, 2021, 2022, 2023]
kegen = kegen.loc[[56, 77, 125]].reset_index(drop=True)

kegen['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    kegen[i] = kegen[i].astype(str)
    kegen[i] = kegen[i].str.replace(',', '.')
    kegen[i] = kegen[i].str.replace(')', '')
    kegen[i] = kegen[i].str.replace(' ', '')
    kegen[i] = kegen[i].str.replace('\xa0', '')
    kegen[i] = kegen[i].astype(float)

kegen = pd.melt(kegen, id_vars=['Indicator'], var_name='year', value_name='value')
kegen = kegen.pivot(index='year', columns='Indicator', values='value').reset_index()
kegen.insert(0, 'rayon', 'Kegen')
kegen.columns.name = None

In [157]:
karasay = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Карасайский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

karasay.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
karasay = karasay.loc[[56, 77, 125]].reset_index(drop=True)

karasay['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    karasay[i] = karasay[i].astype(str)
    karasay[i] = karasay[i].str.replace(',', '.')
    karasay[i] = karasay[i].str.replace(')', '')
    karasay[i] = karasay[i].str.replace(' ', '')
    karasay[i] = karasay[i].str.replace('\xa0', '')
    karasay[i] = karasay[i].astype(float)

karasay = pd.melt(karasay, id_vars=['Indicator'], var_name='year', value_name='value')
karasay = karasay.pivot(index='year', columns='Indicator', values='value').reset_index()
karasay.insert(0, 'rayon', 'Karasay')
karasay.columns.name = None

In [158]:
rayimbek = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Райымбекский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

rayimbek.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
rayimbek = rayimbek.loc[[56, 77, 125]].reset_index(drop=True)

rayimbek['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    rayimbek[i] = rayimbek[i].astype(str)
    rayimbek[i] = rayimbek[i].str.replace(',', '.')
    rayimbek[i] = rayimbek[i].str.replace(')', '')
    rayimbek[i] = rayimbek[i].str.replace(' ', '')
    rayimbek[i] = rayimbek[i].str.replace('\xa0', '')
    rayimbek[i] = rayimbek[i].astype(float)

rayimbek = pd.melt(rayimbek, id_vars=['Indicator'], var_name='year', value_name='value')
rayimbek = rayimbek.pivot(index='year', columns='Indicator', values='value').reset_index()
rayimbek.insert(0, 'rayon', 'Rayimbek')
rayimbek.columns.name = None

for i in [2018, 2019, 2020, 2021, 2022, 2023]:
    rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
    rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
    rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])

/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:22: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'agriculture'] = float(rayimbek.loc[rayimbek['year'] == i, 'agriculture']) + float(kegen.loc[kegen['year'] == i, 'agriculture'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:23: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'production'] = float(rayimbek.loc[rayimbek['year'] == i, 'production']) + float(kegen.loc[kegen['year'] == i, 'production'])
/var/folders/ml/hdf1b15d34z7ct5h7ynlglqh0000gn/T/ipykernel_12817/2088141972.py:24: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  rayimbek.loc[rayimbek['year'] == i, 'retail'] = float(rayimbek.loc[rayimbek['year'] == i, 'retail']) + float(kegen.loc[kegen['year'] == i, 'retail'])

In [159]:
talgar = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Талгарский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

talgar.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
talgar = talgar.loc[[56, 77, 125]].reset_index(drop=True)

talgar['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    talgar[i] = talgar[i].astype(str)
    talgar[i] = talgar[i].str.replace(',', '.')
    talgar[i] = talgar[i].str.replace(')', '')
    talgar[i] = talgar[i].str.replace(' ', '')
    talgar[i] = talgar[i].str.replace('\xa0', '')
    talgar[i] = talgar[i].astype(float)

talgar = pd.melt(talgar, id_vars=['Indicator'], var_name='year', value_name='value')
talgar = talgar.pivot(index='year', columns='Indicator', values='value').reset_index()
talgar.insert(0, 'rayon', 'Talgar')
talgar.columns.name = None

In [160]:
uyghur = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Уйгурский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

uyghur.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
uyghur = uyghur.loc[[56, 77, 125]].reset_index(drop=True)

uyghur['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    uyghur[i] = uyghur[i].astype(str)
    uyghur[i] = uyghur[i].str.replace(',', '.')
    uyghur[i] = uyghur[i].str.replace(')', '')
    uyghur[i] = uyghur[i].str.replace(' ', '')
    uyghur[i] = uyghur[i].str.replace('\xa0', '')
    uyghur[i] = uyghur[i].astype(float)

uyghur = pd.melt(uyghur, id_vars=['Indicator'], var_name='year', value_name='value')
uyghur = uyghur.pivot(index='year', columns='Indicator', values='value').reset_index()
uyghur.insert(0, 'rayon', 'Uyghur')
uyghur.columns.name = None

In [161]:
ile = pd.read_excel("../Data/Controls/Almaty_All.xls", sheet_name="Илийский", header=3, usecols='B, AB:AI', nrows=130, na_values=['x', 'х', '-', '', ' ', '...'])

ile.columns = ['Indicator', 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
ile = ile.loc[[56, 77, 125]].reset_index(drop=True)

ile['Indicator'] = ['agriculture', 'production', 'retail']

for i in [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]:
    ile[i] = ile[i].astype(str)
    ile[i] = ile[i].str.replace(',', '.')
    ile[i] = ile[i].str.replace(')', '')
    ile[i] = ile[i].str.replace(' ', '')
    ile[i] = ile[i].str.replace('\xa0', '')
    ile[i] = ile[i].astype(float)

ile = pd.melt(ile, id_vars=['Indicator'], var_name='year', value_name='value')
ile = ile.pivot(index='year', columns='Indicator', values='value').reset_index()
ile.insert(0, 'rayon', 'Ile')
ile.columns.name = None

In [162]:
almaty_controls = pd.concat([taldykorgan, tekeli, aksu, alakol, kerbulak, koksu, karatal, panfilov, sarkan, yeskeldi, konayev, balkhash, enbekshikazak, zhambyl, karasay, rayimbek, talgar, uyghur, ile], ignore_index=True)
almaty_controls

                rayon  year    agriculture  production    retail
0    Taldykorgan_city  2022        25868.4      125703  111957.2
1    Taldykorgan_city  2023        28315.5    139586.1    121794
2    Taldykorgan_city  2024      31986.418  166554.818  137325.6
3         Tekeli_city  2022         5460.2     29201.3    8447.9
4         Tekeli_city  2023         9566.4     36590.9    8914.7
..                ...   ...            ...         ...       ...
97                Ile  2019   78623.591785    323504.0   75497.1
98                Ile  2020        89322.3    482686.5   80413.3
99                Ile  2021        94182.9    537141.9   86168.0
100               Ile  2022       108355.9    712553.7  100200.5
101               Ile  2023  125078.501027    717105.0  106412.0

[102 rows x 5 columns]

## PPI

In [163]:
almaty_ppi = pd.read_excel("../Data/PPI/Almaty.xls", header=5, usecols='Z:AF', nrows=238, na_values=['x', 'х', '-', '', ' ', '...'])

almaty_ppi.columns = [2016, 2017, 2018, 2019, 2020, 2021, 2022]

rayons = list(almaty_inv['rayon'].unique())

dfs = []

for rayon in rayons:
    df_temp = pd.DataFrame({
        'rayon': rayon,
        'year': range(2016, 2023),
        'ppi': almaty_ppi.values[0]
    })
    dfs.append(df_temp)

almaty_ppi = pd.concat(dfs, ignore_index=True)

almaty_ppi

                rayon  year    ppi
0    Taldykorgan_city  2016  111.4
1    Taldykorgan_city  2017  104.6
2    Taldykorgan_city  2018  107.2
3    Taldykorgan_city  2019  105.9
4    Taldykorgan_city  2020  105.4
..                ...   ...    ...
135       Alatau_city  2018  107.2
136       Alatau_city  2019  105.9
137       Alatau_city  2020  105.4
138       Alatau_city  2021  107.5
139       Alatau_city  2022  115.0

[140 rows x 3 columns]

## Combine together

In [164]:
dfs = [almaty_inv, almaty_empl, almaty_controls, almaty_ppi]

almaty_merged = reduce(lambda left, right: pd.merge(left, right, on=['rayon', 'year'], how='outer'), dfs)

almaty_merged

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year,employment,agriculture,production,retail,ppi
0,Aksu,12974898.0,115616.0,21135,338507.0,Almaty,2016,18.9,NaN,NaN,NaN,111.4
1,Aksu,12974898.0,115616.0,544,1379173.0,Almaty,2017,18.9,NaN,NaN,NaN,104.6
2,Aksu,12974898.0,115616.0,2228,1261975.0,Almaty,2018,18.1,NaN,NaN,NaN,107.2
3,Aksu,12974898.0,115616.0,115616,7185253.0,Almaty,2019,18.1,NaN,NaN,NaN,105.9
4,Aksu,14688817.0,1169390.0,1169390,7579270.0,Almaty,2020,17.4,NaN,NaN,NaN,105.4
...,...,...,...,...,...,...,...,...,...,...,...,...
174,Zhambyl,20079790.0,4594545.0,1294715,9991101.0,Almaty,2020,81.3,63252.2,20051.6,15585.7,105.4
175,Zhambyl,21363798.0,5167718.0,4683327,12520896,Almaty,2021,81.1,65931.7,22136.3,16729.2,107.5
176,Zhambyl,31782899.0,5970398.0,5970398.0,10750287.0,Almaty,2022,78.1,80803.2,23505.1,16163.1,115.0
177,Zhambyl,30223976.0,15128599.0,15128599.0,15104859.0,Almaty,2023,78.4,80627.025943,21456.4,23717.5,NaN
178,Zhambyl,53175462.0,59797102.0,59797102.0,23714834.0,Almaty,2024,NaN,NaN,NaN,NaN,NaN

# Karagandy oblast and Ulytau oblast

## Investments

### 2022-2024

In [168]:
ulytau_all_2022 = pd.read_excel("../Data/Investments/Ulytau/2022_Investments.xls", sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_all_2023 = pd.read_excel("../Data/Investments/Ulytau/2023_Investments.xlsx", sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_all_2024 = pd.read_excel("../Data/Investments/Ulytau/2024_Investments.xlsx", sheet_name='16', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

ulytau_non_2022 = pd.read_excel("../Data/Investments/Ulytau/2022_Investments.xls", sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_non_2023 = pd.read_excel("../Data/Investments/Ulytau/2023_Investments.xlsx", sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
ulytau_non_2024 = pd.read_excel("../Data/Investments/Ulytau/2024_Investments.xlsx", sheet_name='17', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [169]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [ulytau_all_2022, ulytau_all_2023, ulytau_all_2024]:
    df.columns = all_columns
    df.drop(3, inplace=True)
    df.reset_index(drop=True, inplace=True)

for df in [ulytau_non_2022, ulytau_non_2023, ulytau_non_2024]:
    df.columns = non_columns
    df.drop(3, inplace=True)
    df.reset_index(drop=True, inplace=True)
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Zhezkazgan_city', 'Karazhal_city', 'Satpayev_city', 'Zhanaarka', 'Ulytau']

for df in [ulytau_all_2022, ulytau_all_2023, ulytau_all_2024, ulytau_non_2022, ulytau_non_2023, ulytau_non_2024]:
    df['rayon'] = rayon_names

ulytau_2022 = ulytau_all_2022.merge(ulytau_non_2022, on='rayon')
ulytau_2023 = ulytau_all_2023.merge(ulytau_non_2023, on='rayon')
ulytau_2024 = ulytau_all_2024.merge(ulytau_non_2024, on='rayon')

dfs = [ulytau_2022, ulytau_2023, ulytau_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Karagandy'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

In [170]:
ulytau_2022

,rayon,l_all_inv,f_all_inv,f_nonextr_inv,l_nonextr_inv,oblast,year
0,Zhezkazgan_city,33633647.0,9521918.0,9521918.0,24556304.0,Karagandy,2022
1,Karazhal_city,0.0,0.0,0.0,1108912.0,Karagandy,2022
2,Satpayev_city,48045657.0,2323675.0,2323675.0,44168892.0,Karagandy,2022
3,Zhanaarka,26563453.0,486362.0,0.0,23294146.0,Karagandy,2022
4,Ulytau,0.0,0.0,0.0,4970789.0,Karagandy,2022

In [172]:
karagandy_all_2022 = pd.read_excel("../Data/Investments/Karagandy/2022_Investments.xls", sheet_name='13', header=4, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_all_2023 = pd.read_excel("../Data/Investments/Karagandy/2023_Investments.xls", sheet_name='19', header=3, usecols='A, C, F', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_all_2024 = pd.read_excel("../Data/Investments/Karagandy/2024_Investments.xls", sheet_name='14', header=3, usecols='A, C, E', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

karagandy_non_2022 = pd.read_excel("../Data/Investments/Karagandy/2022_Investments.xls", sheet_name='14', header=4, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_non_2023 = pd.read_excel("../Data/Investments/Karagandy/2023_Investments.xls", sheet_name='20', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)
karagandy_non_2024 = pd.read_excel("../Data/Investments/Karagandy/2024_Investments.xls", sheet_name='15', header=3, usecols='A, B, D', na_values=['x', 'х', '-', '', ' ']).fillna(0).drop(0).reset_index(drop=True)

In [173]:
all_columns = ['rayon', 'l_all_inv', 'f_all_inv']
non_columns = ['rayon', 'all_nonextr_inv', 'f_nonextr_inv']

for df in [karagandy_all_2022, karagandy_all_2023, karagandy_all_2024]:
    df.columns = all_columns
    df.drop(6, inplace=True)
    df.reset_index(drop=True, inplace=True)

for df in [karagandy_non_2022, karagandy_non_2023, karagandy_non_2024]:
    df.columns = non_columns
    df.drop(6, inplace=True)
    df.reset_index(drop=True, inplace=True)
    df['l_nonextr_inv'] = df['all_nonextr_inv'] - df['f_nonextr_inv']
    df.drop('all_nonextr_inv', axis=1, inplace=True)

rayon_names = ['Karagandy_city', 'Balkhash_city', 'Priozersk_city', 'Saran_city', 'Temirtau_city', 'Shakhtinsk_city', 'Abay', 'Aktogay', 'Bukhar_zhyrau', 'Karkaraly', 'Nura', 'Osakarov', 'Shet']

dfs = [karagandy_all_2022, karagandy_all_2023, karagandy_all_2024, karagandy_non_2022, karagandy_non_2023, karagandy_non_2024]

for i in range(6):
    df = dfs[i]
    df['rayon'] = rayon_names

kar_2022 = karagandy_all_2022.merge(karagandy_non_2022, on='rayon')
kar_2023 = karagandy_all_2023.merge(karagandy_non_2023, on='rayon')
kar_2024 = karagandy_all_2024.merge(karagandy_non_2024, on='rayon')

dfs = [kar_2022, kar_2023, kar_2024]

for i in range(3):
    df = dfs[i]
    df['oblast'] = 'Karagandy'
    if i == 0:
        df['year'] = 2022
    elif i == 1:
        df['year'] = 2023
    else:
        df['year'] = 2024

karagandy_2022 = pd.concat([ulytau_2022, kar_2022], ignore_index=True)
karagandy_2023 = pd.concat([ulytau_2023, kar_2023], ignore_index=True)
karagandy_2024 = pd.concat([ulytau_2024, kar_2024], ignore_index=True)

### 2014-2021